src/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
]

src/mylittleapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

app_name = 'apphome'
urlpatterns = [
    path('', index, name='home'),
    path('accounts/', include('accounts.urls')),
    path('story/', include('story.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # # Common View
    # path('', views.index, name='index'),
    # path('<int:question_id>/detail', views.details, name='details'),
    # path('<int:question_id>/results', views.result, name='results'),

    # Generic View
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.DetailsView.as_view(), name='details'),
    path('<int:pk>/results', views.ResultsView.as_view(), name='results'),

    path('<int:question_id>/vote', views.vote, name='vote'),
]

src/story/urls.py
from django.urls import path
from . import views


app_name = 'story'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new', views.CreateView.as_view(), name='new'),
    path('<int:pk>', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/edit', views.EditView.as_view(), name='edit'),
    path('<int:pk>/del', views.DeleteView.as_view(), name='delete'),
]

src/accounts/models.py
from django.db import models

# Create your models here.

src/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    # Define how a column (was_published_recently) displays in admin view
    # Note it is in class but after and out of method
    was_published_recently.admin_order_field = 'pub_date'  # sort as pub_date
    was_published_recently.boolean = True  # tell the value is boolian
    was_published_recently.short_description = 'Published recently?'  # name to display


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

src/story/models.py
from django.db import models
from django.conf import settings

User = settings.AUTH_USER_MODEL


class Story(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=False)
    story_img = models.ImageField(
        default='default_story_iimg.jpg', upload_to='story_pic')
    content = models.TextField(max_length=500)
    pub_date = models.DateTimeField('Date Published', auto_now=True)

    def __str__(self):
        return self.title

src/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signin(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('story:index')
    else:
        form = AuthenticationForm()
        return render(request, 'accounts/signin.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('story:index')
    else:
        form = UserCreationForm()
        return render(request, 'accounts/signup.html', {'form': form})


def signout(request):
    logout(request)
    return redirect('home')

src/mylittleapp/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

src/polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect, HttpResponseForbidden
from django.template import loader
from .models import Question, Choice
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# # Common View
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}

#     # # Vanila Method
#     # template = loader.get_template('polls/index.html')
#     # return HttpResponse(template.render(context, request))

#     # Shortcut Method
#     return render(request, 'polls/index.html', context)


# def details(request, question_id):
#     # # Vanila Method
#     # try:
#     #     question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist as onject_not_found:
#     #     raise Http404("Question with id {} not found!!".format(question_id))
#     # return HttpResponse("Welcome to details for Question {}".format(question_id))

#     # Shortcut Method
#     question = get_object_or_404(Question, pk=question_id)
#     context = {'question': question}
#     return render(request, 'polls/details.html', context)

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     context = {'question': question}
#     return render(request, 'polls/results.html', context)


# GenericView

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        # return Question.objects.order_by('-pub_date')[:5]
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailsView(generic.DetailView):
    model = Question
    template_name = 'polls/details.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    if request.POST:
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(
                pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist, NameError) as choice_error:
            return render(request, 'polls/details.html', {
                'question': question,
                'error_message': 'You did not selected a correct option!'
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()
            return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))
    else:
        return HttpResponseForbidden()

src/story/views.py
from django.shortcuts import render
from django.views import generic
from .models import Story


class IndexView(generic.ListView):
    model = Story
    template_name = 'story/index.html'
    context_object_name = 'stories'


class DetailView(generic.DetailView):
    model = Story
    template_name = 'story/detail.html'
    context_object_name = 'story'


class CreateView(generic.CreateView):
    model = Story
    template_name = 'story/create.html'


class EditView(generic.UpdateView):
    model = Story
    template_name = 'story/edit.html'
    context_object_name = 'story'


class DeleteView(generic.DeleteView):
    model = Story
    context_object_name = 'story'

src/accounts/templates/accounts/signin.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'accounts:signin' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Login">
</form>
{% endblock content %}

src/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
</form>
{% endblock content %}

src/polls/templates/polls/details.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">

<h3>{{ question.question_text }}</h3>
{% if error_message %}
<p class="error_msg">
        <bold>{{ error_message }}</bold>
    </p>
{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    <br>
    {% endfor %}
    <input type="submit" value="Submit vote">
</form>
{% endblock content %}

src/polls/templates/polls/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:details' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<h3>No polls are available</h3>
{% endif %}
{% endblock content %}

src/polls/templates/polls/results.html
{% extends "base.html" %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">

<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:details' question.id %}">Vote again?</a>
{% endblock content %}

src/story/templates/story/create.html
{% extends "base.html" %}

{% block content %}
<h2>Story create view</h2>

{% endblock content %}

src/story/templates/story/detail.html
{% extends "base.html" %}

{% block content %}
<h2>Story detail view</h2>

{% endblock content %}

src/story/templates/story/edit.html
{% extends "base.html" %}

{% block content %}
<h2>Story edit view</h2>

{% endblock content %}

src/story/templates/story/index.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'story/style.css' %}">
<h2>Stories</h2>
{% if stories %}
{% for story in stories %}
<div class="story-card">
    <h4>{{ story.title }}</h4>
    {% if story.story_img %}
    <img src="/media/{{ story.story_img }}" alt="Media Image" height="250px">
    {% endif %}
    <p>{{ story.content  }}</p>
    <br>
    <a href="{% url 'story:detail' story.id %}">View</a>
</div>
{% endfor %}
{% else %}
<h4>Sory no story to display</h4>
{% endif %}
{% endblock content %}

src/templates/base.html
<h1>My Little Django Web App</h1>
{% if user.is_authenticated %}
<h5>Logged in as {{ user.get_username }}</h5>
{% else %}
<h5>Not logged in</h5>
{% endif %}
<h3>Site links</h3>
<h4><a href="/">Home</a></h4>
<h4>Polls</h4>
<a href="{% url 'polls:index' %}">Polls Index</a>
<h4>Story</h4>
<a href="{% url 'story:index' %}">Story Index</a>
<h4>Accounts</h4>
<a href="{% url 'accounts:signin' %}">Signin</a>
<a href="{% url 'accounts:signup' %}">Signup</a>
<a href="{% url 'accounts:signout' %}">Signout</a>

{% block content %}

{% endblock content %}

src/templates/index.html
<h1>Welcome to My Little App</h1>